# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-29 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_item', to='order.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_restaurant', to='accounts.Restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_waiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
